            <br clear="all" />
            <div class="msg_top"></div>
            <div class="msg_middle">
                <p id="sous_titre">L'internet facile pour tous...</p>
                <img src="/img/site/aide01.gif" id="aide01" title="<?php echo $this->myviewhelper()->templateVars['partial']['refTitle']; ?>" />
                <p class="indent">Pour visualiser les pages de ce site de façon optimale, nous vous recommandons des paramétrages et solutions logiciels conforment aux normalisations et standards actuelles. Vous trouverez sur cette page les divers aides et conseils pour une qualité et une facilité de navigation accrue, avec bien sur des notions d'accessibilité pour les personnes souffrant d'un handicap contraignant à une utilisation normal d'internet. Un point d'honneur sera mis sur cette notion d'accessibilité pour que ce site ne soit pas inaccessible à ces personnes.</p>
                <br clear="all" />
                <div class="msg_top"></div>
                <div class="msg_middle">
                   <h2>Sommaire :</h2>
                   <ol class="sommaire">
                      <li><a href="#navigateurs" class="JS_bubble_chapitre" title="Navigateur 100% compatible" rel="smooth_anchors">Les différents navigateurs pris en charge</a></li>
                      <li><a href="#plugins" class="JS_bubble_chapitre" title="Solutions plugiciels (plugin)" rel="smooth_anchors">Solutions plugiciels (plugin) pour votre navigateur</a></li>
                      <li><a href="#param_navigateur :" class="JS_bubble_chapitre" title="Paramètres normalement par defaut" rel="smooth_anchors">Paramètres du navigateur</a></li>
                      <li><a href="#resolutions" class="JS_bubble_chapitre" title="Résolution d'écran" rel="smooth_anchors">Résolution d'écran prisent en charge</a></li>
                      <li><a href="#Accessibilite" class="JS_bubble_chapitre" title="Accessibilité" rel="smooth_anchors">Accessibilité et support pour les personnes souffrant d'un handicap</a></li>
                      <li><a href="#logiciels" class="JS_bubble_chapitre" title="Solutions logiciels gratuites et libres" rel="smooth_anchors">Solutions logiciels "open sources"</a></li>
                   </ol>
                </div>
                <div class="msg_bottom"></div>
                <hr />
                <a id="smooth_1" name="navigateurs"></a>
                <h3><i>Navigateurs pris en charge :</i></h3>
                <p class="indent">Voici ci-dessous la liste des différents navigateurs internet compatible à la bonne navigation sur ce site. Ces navigateurs sont ordonnancées dans un ordre logique de préférences quand au respect des standards par ceux-ci en vue des différents tests ACID ainsi que de leur notoriété.</p>
                <ul>
                   <li>Mozilla Firefox à partir des versions 1.x</li>
                   <li>Iceweasel à partir des versions 1.x</li>
                   <li>Safari  à partir des versions 1.x</li>
                   <li>Chrome  à partir des versions 1.x</li>
                   <li>Microsoft Internet Explorer à partir des versions 4.x</li>
                   <li>Opéra à partir des versions 7.x</li>
                   <li>Netscape Navigator à partir des versions 4.x</li>
                   <li>Konqueror à partir des versions 3.x</li>
                   <li>...</li>
                </ul>
                <div id="go_top">
                    <a href="#top" class="JS_bubble_notitle" title="haut de page">&nbsp;</a>
                </div>
                <hr />
                <a id="smooth_2" name="plugins"></a>
                <h3><i>Solutions plugiciels (plugin) pour votre navigateur :</i></h3>
                <p class="indent">Voici ci-dessous la liste des différents plugiciels standards requis pour une navigation correcte sur internet. Merci de bien vouloir vous assurez que ceux-ci soient bien installés sur votre navigateur et qu'ils sont bien mis à jour.</p>
                <p class="center"><br /><a href="http://www.adobe.com/fr/products/acrobat/readstep2.html" target="_blank" class="JS_bubble_lienExt" title="Télécharger Acrobat Reader !"><img src="http://beroots.local.loc/0_img/get_adobe_reader_160x40.gif" style="border: 0;" alt="Télécharger Acrobat Reader !" /></a>
                  <br /><br /><a href="http://www.adobe.com/shockwave/download/download.cgi?P1_Prod_Version=Shockwave&Lang=French&P5_Language=French&promoid=BPCJI" target="_blank" class="JS_bubble_lienExt" title="Télécharger Shockwave Player !"><img src="http://beroots.local.loc/0_img/get_shockwave_player_160x40.gif" style="border: 0;" alt="Télécharger Shockwave Player !" /></a>
                  <br /><br /><a href="http://www.adobe.com/shockwave/download/download.cgi?P1_Prod_Version=ShockwaveFlash&Lang=French" target="_blank" class="JS_bubble_lienExt" title="Télécharger Flash Player !"><img src="http://beroots.local.loc/0_img/get_flash_player_160x40.gif" style="border: 0;" alt="Télécharger Flash Player !" /></a>
                </p>
                <div id="go_top">
                    <a href="#top" class="JS_bubble_notitle" title="haut de page">&nbsp;</a>
                </div>
                <hr />
                <a id="smooth_3" name="param_navigateur"></a>
                <h3><i>Paramètres du navigateur :</i></h3>
                <p class="indent">Voici la liste des paramètres essentiels au bon fonctionnement de ce site web sur votre navigateur. Ces paramètres sont normalement définis par défaut. Si toutefois vous rencontriez des difficultés à l'utilisation de ce site web, assurer vous du bon paramétrage de ces derniers. Ceux-ci se trouve généralement sur votre navigateur, dans le menu "options" (ou "outils"=>"options", ou encore "préférences", "paramètre", ...).</p>
                <ul>
                   <li>Autoriser JavaScript</li>
                   <li>Autoriser Java</li>
                   <li>Autoriser l'utilisation des cookies</li>
                </ul>
                <div id="go_top">
                    <a href="#top" class="JS_bubble_notitle" title="haut de page">&nbsp;</a>
                </div>
                <hr />
                <a id="smooth_4" name="resolutions"></a>
                <h3><i>Résolution d'écran prisent en charge :</i></h3>
                <p class="indent">Ce site web est optimisé de façon à s'afficher de manière optimale sous les résolutions d'écran les plus courantes. La résolution d'écran <i>540 x 480</i> n'est plus prise en compte car désormais trop peut utilisée par les internautes.</p>
                <ul>
                   <li>Résolution minimum : 800 x 600</li>
                   <li>Résolution conseillée : 1024 x 768</li>
                   <li>Toutes autres résolutions supérieures</li>
                </ul>
                <div id="go_top">
                    <a href="#top" class="JS_bubble_notitle" title="haut de page">&nbsp;</a>
                </div>
                <hr />
                <a id="smooth_5" name="Accessibilite"></a>
                <h3><i>Accessibilité :</i></h3>
                <p class="indent">Voici la liste des divers conseils et solutions pour une navigation simplifié sur ce site.</p>
                <ul>
                   <li>Utilisation du mode plein écran</li>
                   <li>Utilisation du mode zoom</li>
                   <li>Modification de la taille de police dans les limites du raisonnable</li>
                   <li>Utilisation de la navigation par tabulation</li>
                   <li>utilisation de la loupe</li>
                </ul>
                <div id="go_top">
                    <a href="#top" class="JS_bubble_notitle" title="haut de page">&nbsp;</a>
                </div>
                <hr />
                <a id="smooth_6" name="logiciels"></a>
                <h3><i>Solutions logiciels "open sources" :</i></h3>
                <p class="indent">Voici ci-dessous une liste de logiciel, tous gratuits et de grande renommée. Ces logiciels sont une sélection de projet "open sources" vivement recommandé.</p>
                <p class="center">
                    <a href="http://www.mozilla-europe.org/fr/products/firefox/" target="_blank" class="JS_bubble_lienExt" title="Télécharger Firefox ! Navigateur internet de premier choix."><img src="http://beroots.local.loc/0_img/get_firefox.gif" style="border: 0;" alt="Télécharger Firefox !" /></a>
                    <br /><br />
                    <a href="http://fr.openoffice.org/about-downloads.html" target="_blank" class="JS_bubble_lienExt" title="Télécharger Open Office ! Suite logiciel bureautique (traitement de texte, tableur,...)"><img src="http://beroots.local.loc/0_img/get_openoffice.gif" style="border: 0;" alt="Télécharger Open Office !" /></a>
                </p>
            </div>
            <div class="msg_bottom"></div>            